#!/usr/bin/env python
"""Phase B runner — Reflected Mechanism Ablations (TinyStories only).

Sweeps the reflected router knobs on TinyStories while keeping Top-2 and
DeepSeek-LFB as fixed reference baselines.

Per the publication plan:
  - Sweep: ``pressure_lr ∈ {0.01, 0.05, 0.1}``,
           ``capacity_factor ∈ {0.5, 1.0}``,
           ``shared_experts ∈ {0, 1}``,
           ``pressure_warmup_steps ∈ {0, 1000}``,
           ``learnable_bias ∈ {off, on}``
  - Optional: ``gate_function ∈ {softmax, sigmoid}``
  - All ablations use **1 seed** (to preserve compute budget)
  - Reference baselines (Top-2, DeepSeek-LFB) run at default config, 1 seed
  - DO NOT use FineWeb for ablations

The ablation grid is generated by ``src/moe_route/ablation/grid.py`` as
lightweight ``AblationPoint`` descriptors, which this runner converts to
``ExperimentSpec`` objects for execution.

Usage:
  python -m studies.runners.run_phase_b
  python -m studies.runners.run_phase_b --dry-run
  python -m studies.runners.run_phase_b --smoke
  python -m studies.runners.run_phase_b --include-gate-sweep
  python -m studies.runners.run_phase_b --strategy full
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))
if str(_REPO_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT / "src"))

from moe_route.ablation.grid import AblationPoint, build_ablation_grid
from studies.utils.experiment_spec import (
    DispatchMode,
    ExperimentSpec,
    PHASE_B_REFERENCE_BASELINES,
    Phase,
)
from studies.utils.runner_base import CONFIG_ROOT, PhaseRunner
from studies.utils.validation import validate_study

STUDY_NAME = "phase_b_ablation_reflected"


def ablation_point_to_spec(point: AblationPoint) -> ExperimentSpec:
    """Convert an ``AblationPoint`` to an ``ExperimentSpec``.

    The conversion bridges the decoupled ablation grid (in ``moe_route``)
    with the experiment orchestration layer (in ``studies/``).  The
    ``experiment_id`` from the ablation point is used as the spec ``name``
    so that it flows through to persistence without double-encoding.
    """
    return ExperimentSpec(
        name=point.experiment_id,
        experiment="tinystories_reflected_v2",
        model="tiny_moe",
        router="reflected_sparse",
        data="tinystories",
        trainer="tinystories",
        is_moe=True,
        dispatch_mode=DispatchMode.SPARSE,
        description=point.description,
        phases=frozenset({Phase.B}),
        # Do NOT pass hydra_overrides to ExperimentSpec — the experiment_id
        # already encodes the full parameter set.  We pass the overrides
        # directly so they are applied at training time, but the spec's
        # experiment_id property returns just `name` (no double-encoding).
        hydra_overrides=point.hydra_overrides,
        tags=dict(point.tags),
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Phase B: Reflected mechanism ablations on TinyStories.\n"
            "Sweeps pressure_lr, capacity_factor, shared_experts, "
            "pressure_warmup_steps, and learnable_bias."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--include-gate-sweep",
        action="store_true",
        help="Include gate_function sweep (softmax, sigmoid). Optional per plan.",
    )
    parser.add_argument(
        "--strategy",
        choices=["oat", "full"],
        default="oat",
        help="Ablation sweep strategy: 'oat' (one-at-a-time, default) or 'full' (Cartesian product).",
    )
    parser.add_argument(
        "--skip-references",
        action="store_true",
        help="Skip the Top-2 and DeepSeek-LFB reference baseline runs.",
    )
    parser.add_argument(
        "--run-prefix",
        default="phase_b",
        help="Prefix for run names.",
    )
    parser.add_argument(
        "--checkpoint-root",
        default="artifacts/checkpoints/phase_b",
        help="Root directory for checkpoints.",
    )
    parser.add_argument(
        "--result-root",
        default="artifacts/results",
        help="Root directory for result persistence.",
    )
    parser.add_argument(
        "--nproc-per-node",
        type=int,
        default=1,
        help="GPUs per node for distributed training.",
    )
    parser.add_argument("--skip-prepare", action="store_true")
    parser.add_argument("--rebuild-data", action="store_true")
    parser.add_argument("--smoke", action="store_true", help="Smoke test mode.")
    parser.add_argument("--dry-run", action="store_true", help="Print commands only.")
    parser.add_argument(
        "--set",
        action="append",
        default=[],
        metavar="KEY=VALUE",
        help="Additional Hydra override.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    # Build ablation grid (lightweight AblationPoint descriptors)
    grid = build_ablation_grid(
        strategy=args.strategy,
        include_gate_sweep=args.include_gate_sweep,
    )

    # Convert to ExperimentSpecs
    ablation_specs = [ablation_point_to_spec(p) for p in grid]

    # Combine ablation specs with reference baselines
    all_specs: list[ExperimentSpec] = list(ablation_specs)
    if not args.skip_references:
        all_specs.extend(PHASE_B_REFERENCE_BASELINES)

    print(f"\n[{STUDY_NAME}] Ablation strategy: {args.strategy}")
    print(f"[{STUDY_NAME}] Ablation grid: {len(ablation_specs)} reflected variants")
    if not args.skip_references:
        print(f"[{STUDY_NAME}] Reference baselines: {len(PHASE_B_REFERENCE_BASELINES)}")
    print(f"[{STUDY_NAME}] Total experiments: {len(all_specs)}")

    # Build runner
    runner = PhaseRunner(
        study_name=STUDY_NAME,
        phase=Phase.B,
        specs=all_specs,
        result_root=args.result_root,
        run_prefix=args.run_prefix,
    )

    # Build schedule (Phase B uses 1 seed per spec)
    runs = runner.build_schedule()

    # Validate
    report = validate_study(runs, CONFIG_ROOT, STUDY_NAME)
    report.print_report()
    report.raise_if_failed()

    # Print plan
    runner.print_plan(runs)

    # Prepare data (TinyStories only for ablations)
    if not args.skip_prepare:
        data_config = "tinystories_smoke" if args.smoke else "tinystories"
        runner.prepare_data(data_config, rebuild=args.rebuild_data, dry_run=args.dry_run)

    # Execute
    results = runner.execute(
        runs,
        checkpoint_root=args.checkpoint_root,
        common_overrides=args.set,
        nproc_per_node=args.nproc_per_node,
        skip_prepare=not args.skip_prepare,
        dry_run=args.dry_run,
        smoke=args.smoke,
    )

    # Report
    if not args.dry_run:
        runner.aggregate_and_summarize(runs)
        runner.print_results_table(runs)

    # Exit status
    failed = [r for r, ok in results if not ok]
    if failed:
        print(f"\n[{STUDY_NAME}] {len(failed)} run(s) FAILED:")
        for run, _ in [(r, ok) for r, ok in results if not ok]:
            print(f"  ✗ {run.run_name}")
        raise SystemExit(1)

    print(f"\n[{STUDY_NAME}] All {len(results)} run(s) completed successfully.\n")


if __name__ == "__main__":
    main()
